// /* eslint-disable react/prop-types */
// import { createContext, useState } from "react";

// export const LanguageContext = createContext();

// export function LanguageProvider({ children }) {
//   const [language, setLanguage] = useState("English");

//   const translations = {
//     English: {
//       welcome: "Welcome, {name}!",
//       overview: "Here's a quick overview of your dashboard. Explore key metrics and recent activities below.",
//       totalUsers: "Total Users",
//       revenue: "Revenue",
//       orders: "Orders",
//       activeSessions: "Active Sessions",
//       recentActivity: "Recent Activity",
//       userGrowth: "User Growth",
//       activity1: "User John Smith updated profile",
//       activity2: "New order #1234 placed",
//       activity3: "Report generated by Jane Doe",
//     },
//     Spanish: {
//       welcome: "¡Bienvenido, {name}!",
//       overview: "Aquí tienes un resumen rápido de tu panel. Explora métricas clave y actividades recientes a continuación.",
//       totalUsers: "Usuarios Totales",
//       revenue: "Ingresos",
//       orders: "Pedidos",
//       activeSessions: "Sesiones Activas",
//       recentActivity: "Actividad Reciente",
//       userGrowth: "Crecimiento de Usuarios",
//       activity1: "El usuario John Smith actualizó su perfil",
//       activity2: "Nuevo pedido #1234 realizado",
//       activity3: "Informe generado por Jane Doe",
//     },
//     French: {
//       welcome: "Bienvenue, {name} !",
//       overview: "Voici un aperçu rapide de votre tableau de bord. Explorez les métriques clés et les activités récentes ci-dessous.",
//       totalUsers: "Utilisateurs Totaux",
//       revenue: "Revenus",
//       orders: "Commandes",
//       activeSessions: "Sessions Actives",
//       recentActivity: "Activité Récente",
//       userGrowth: "Croissance des Utilisateurs",
//       activity1: "L'utilisateur John Smith a mis à jour son profil",
//       activity2: "Nouvelle commande #1234 passée",
//       activity3: "Rapport généré par Jane Doe",
//     },
//   };

//   return (
//     <LanguageContext.Provider value={{ language, setLanguage, translations }}>
//       {children}
//     </LanguageContext.Provider>
//   );
// }